version: '3.8'

services:
  azure-function:
    image: test-function-image
    container_name: Test-function-container
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - SqlConnectionString=Server=localhost;Database=Test_Db;Trusted_Connection=True;TrustServerCertificate=True
    ports:
      - "7071:80"  
    depends_on:
      - sqlserver  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SqlServer
    environment: test
      SA_PASSWORD: "Chandan@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
